// angular 5.0/app/components/files-view/files-view.component.ts
/**
 * @rxdoc component
 * @name filesView
 *
 * @description
 * filesView is a UI Component that allows to display, download, remove files.
 * Component is displayed a thumbnail and name of a file.
 * Also, you can configure remove, download file.
 *
 * Example:
 * <files-view [files]="files"
 *             [removeFile]="removeFile"
 *             [downloadFile]="downloadFile">
 * </files-view>
 */

import { Component, Input } from '@angular/core';

@Component({
    selector: 'files-view',
    templateUrl: 'files-view.component.html',
    styleUrls: ['files-view.component.css']
})

export class FilesViewComponent {
    @Input() files: Array<Object> = [];
    @Input() removeFile: Function;
    @Input() downloadFile: Function;

    download(index: number) {
        let file:any = this.files[index];

        this.downloadFile(index)
            .then(function (path: string) {
                setTimeout(() => {
                    let a = document.createElement('a');
                    document.body.appendChild(a);
                    a.style.display = 'none';
                    a.href = path;
                    a.download = file.name;
                    a.click();
                    document.body.removeChild(a);
                }, 0);
            })
            .catch(()=>{});
    }
}

<div class="files-view">

    <div class="files-view-wrapper">

        <div class="files-view-item" *ngFor="let file of files; index as $index;">
            <div class="files-view-thumbnail fa"
                 title="{{file.name}}"
                 [ngClass]="file.thumbnail"
                 (click)="download($index)">
                    <img *ngIf="file.preview.backgroundImage" src="{{file.preview.backgroundImage}}"
                         alt="{{file.name}}" />
            </div>

            <div class="files-view-name" (click)="download($index)" title="{{file.name}}">
                {{file.name}}
            </div>

            <span *ngIf="removeFile" class="files-view-remove"
                  (click)="removeFile($index)">
                x
            </span>
        </div>

    </div>

</div>

// react/app/components/Files_View/Files_View.jsx
'use strict';

import React, { Component } from 'react';
import { removeFile } from './../../actions/files';
import store from './../../store';

export default class Files_View extends Component {
    constructor() {
        super();
    }

    /**
     * @param index
     */
    downloadFile(index) {
        let file = this.props.files[index];

        // You have two options here
        // 1. To get content from server
        // 2. By direct path to file

        if (file.content) {
            let blob = new Blob([file.content], { type: file.type });

            // https://github.com/eligrey/FileSaver.js/
            return void saveAs(blob, file.name);
        }

        Files_View.downloadFileByPath('https://en.wikipedia.org/wiki/Basketball');
    }

    /**
     * @param {String} path - direct path to file
     */
    static downloadFileByPath(path) {
        let a = document.createElement('a');
        document.body.appendChild(a);
        a.style.display = 'none';
        a.href = path;
        a.download = file.name;
        a.click();
        document.body.removeChild(a);
    }

    /**
     * @param index
     */
    static removeFile(index) {
        store.dispatch(removeFile(index));
    }

    render() {
        let files = this.props.files;

        if (_.isEmpty(files)) {
            return null;
        }

        return <div>
            <div className="files-view">
                <div className="files-view-wrapper">

                    {files.map((file, index) => {
                       return <div className="files-view-item" key={index}>
                           <div className={"files-view-thumbnail fa " + file.thumbnail}
                                title={file.name}
                                onClick={this.downloadFile.bind(this, index)}>
                               <img className={file.preview.backgroundImage ? 'displayBlock' : 'displayNone'}
                                    src={file.preview.backgroundImage}
                                    alt={file.name} />
                           </div>

                           <div className="files-view-name" onClick={this.downloadFile.bind(this, index)} title={file.name}>
                               {file.name}
                           </div>

                           <span className="files-view-remove" onClick={Files_View.removeFile.bind(this, (index))}>x</span>
                       </div>
                    })}

                </div>
            </div>
        </div>
    }
}
